In [24]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Antoine\Desktop\github_cloned_repo\kernel-methods-challenge\machine-learning-with-kernel-methods-2021\submission_fusion_k_6_svm_c_0.01_gaussian_sigma_1_fusion_strategy.csv')

In [27]:
df = df.set_index('Id')
df

      Bound
Id
0         0
1         0
2         0
3         0
4         0
...     ...
2995      0
2996      1
2997      0
2998      0
2999      0

[3000 rows x 1 columns]

In [30]:
df.to_csv('submission1.csv')

In [34]:
df2 = pd.read_csv('submission1.csv',index_col=0)
df2

      Bound
Id
0         0
1         0
2         0
3         0
4         0
...     ...
2995      0
2996      1
2997      0
2998      0
2999      0

[3000 rows x 1 columns]